language: android

branches:
  only:
    - master
    - /^v\.\d+\.\d+\.\d+$/

jdk:
- oraclejdk8

env:
  global:
    - TERM=dumb
    - secure: "kTKD2QGoxtJJTII61/TKlKLUOI/5JoaEHQWlQxhgAt4+yt3BMMdrrvb81u2TMy6ihOSOr280VTax2HT3X5+mty0ND4Fagd+w5y1Jg4hXAWmBkBv5ffVQAN17LC7M/Ee1oW/7o79A9Xu4Wp7leK0que/wn3kcuAS1i/qYJjWVnBRvkkW2MMg0xtEFBhH8ENIlt/XgfPhWeLY0syUqVce3F51xmVt0zP6CS8iaa4qoIndQl/dENoietAV4OEpAjviJQb1TDqlNAJD83HGLFTDK1HFhjGOstEDb/ak/Y10BfZMr6ClXk4fgze7mAc4/0lOYzf5ft7yMFbwE3gjkPzUF1YBDp3mS2lKIo4VcjyqCJxN9p6NlnzfxCIDfCarr/h/uAJx9gG6miJeKd6X9QHyWPpLh/wHlcimunnC6lIwqhLow7ZedxwEg4xOLf//y9Z8uYQWuAeAxrdZhmaASNLH+TkYd8Bcy4n17ck/Oqud/RSuG0TcQ32IozOZXfzWqPxBSZDUKgbg70J6uhPkm+mZF8MOPj3XbPxJToOQGLK0GKbGDFWS5dnjax/cjmyrl4vvDdh9AAgwamk6aQWF82SrDI2q9roU3VjjMhuVj4H4zm4nVrFxyTXco3SgzkdNMNfanrdX51+LzGqCfUK0aRGhBtC2LOZE62/M3pZUr+u1Lz+M="
    - secure: "HAYVmyNx5dDR8AxRR5dJDuE4WPll7LI1prPTkCW1T3xmxa9kG4UJG5QhkeyKzx7RfvSL43DAJYVCoaX3RubntJI15lbd8uHME2/Kf/D/5EBlVg2cga9Ih5v3eRNNYBsk0W6W7Yp7BqU//ZUHvVuIbJtBQ7e0R5ML53mqPuIN5LTIGkDG31isH7LkMbxUQJoI2j2nZuq1E5YlinX36YgWmGWug81nu9ZEUDhXOy5IhJRJjwiXozpQz2YAZbLzkYgGvJUkoxIIehT3lPyf0rVVJisd24ZZAXW7oJ1c6FfgsGObNW8inTAdrGhsuxXmE/k/hll2sGWWos6v5z0im8ZeLAoborqoMKigmPS5/GLWdUn1n2h4Bm1uPhWlnRVCBaoRWtFwdfD09kyriqCoQfOsYUlGEKQSsYezse5mnzNJ54vHcjCkqJzG2FnyQEqu+TBdTxuxiH5jdNSWXSHLTb4rFnO++2Q9B5wGdv88KJMuBolZbi2ykv2LYAQNo8wvIwFACrjOGLtZmZbSh7fDsGdRIfwPLP6IaH8bgi5VEUnayogCwGqVu/JtHkW10Q4C17D8bU9yC8auYeTwNH5CjcieYhm6zUAH/nK5Zgg8jnknkpmolBl0jEVEkzzgIQ8ecU3E5aAsjiu7ggIdrPSMH0qy5fdblhsaK1E11Gexrh7IpG4="


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24

script: ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true